[project]
name = "bd-project-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask-geopandas>=0.4.3",
    "dask[complete]>=2025.3.0",
    "geopandas>=1.0.1",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
]
